version: "3.8"
services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    env_file:
      - ./nest-backend/.env
    environment:
      TZ: "America/Santiago"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - ia_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis:6
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - ia_network
      
  backend:
    build:
      context: ./nest-backend
      dockerfile: Dockerfile
    container_name: nest-backend
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    networks:
      - ia_network
    env_file:
      - ./nest-backend/.env
      
  frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - ia_network
      
  fast-detect-gpt:
    build:
      context: ./fast-detect-gpt
      dockerfile: Dockerfile
    container_name: fast-detect-gpt
    ports:
      - "8001:8001"
    networks:
      - ia_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


networks:
  ia_network:

volumes:
  postgres_data: