import { Test, TestingModule } from '@nestjs/testing';
import { NotFoundException } from '@nestjs/common';
import { DetectController } from './detect.controller';
import { DetectService } from './detect.service';
import { QueueService } from '../queue/queue.service';

describe('DetectController', () => {
  let controller: DetectController;
  let service: DetectService;
  let queueService: QueueService;

  const mockDetectService = {
    detectWithFastDetectGPT: jest.fn(),
  };

  const mockQueueService = {
    getDetectionJobProgress: jest.fn(),
  };

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      controllers: [DetectController],
      providers: [
        {
          provide: DetectService,
          useValue: mockDetectService,
        },
        {
          provide: QueueService,
          useValue: mockQueueService,
        },
      ],
    }).compile();

    controller = module.get<DetectController>(DetectController);
    service = module.get<DetectService>(DetectService);
    queueService = module.get<QueueService>(QueueService);
  });

  afterEach(() => {
    jest.clearAllMocks();
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  describe('detectWithFastDetectGPT', () => {
    it('should call service with text and return detection result', async () => {
      const createDetectDto = {
        text: 'This is a sample text for AI detection.',
      };

      const expectedResult = {
        ai_score: 75.5,
        ai_result: 'AI' as const,
        criterion: 0.85,
      };

      mockDetectService.detectWithFastDetectGPT.mockResolvedValue(expectedResult);

      const result = await controller.detectWithFastDetectGPT(createDetectDto);

      expect(result).toEqual(expectedResult);
      expect(service.detectWithFastDetectGPT).toHaveBeenCalledWith(createDetectDto);
      expect(service.detectWithFastDetectGPT).toHaveBeenCalledTimes(1);
    });

    it('should handle AI result', async () => {
      const createDetectDto = {
        text: 'This text is likely generated by AI.',
      };

      const aiResult = {
        ai_score: 90.0,
        ai_result: 'AI' as const,
        criterion: 1.2,
      };

      mockDetectService.detectWithFastDetectGPT.mockResolvedValue(aiResult);

      const result = await controller.detectWithFastDetectGPT(createDetectDto);

      expect(result.ai_result).toBe('AI');
      expect(result.ai_score).toBeGreaterThan(50);
    });

    it('should handle Human result', async () => {
      const createDetectDto = {
        text: 'This text is likely written by a human.',
      };

      const humanResult = {
        ai_score: 20.0,
        ai_result: 'Human' as const,
        criterion: -0.5,
      };

      mockDetectService.detectWithFastDetectGPT.mockResolvedValue(humanResult);

      const result = await controller.detectWithFastDetectGPT(createDetectDto);

      expect(result.ai_result).toBe('Human');
      expect(result.ai_score).toBeLessThan(50);
    });
  });

  describe('getDetectionProgress', () => {
    it('should return progress for a valid job ID', async () => {
      const jobId = 'test-job-123';
      const expectedProgress = {
        percentage: 45,
        status: 'Processing chunk 5 of 10...',
        currentDoc: 'test-document.txt',
        chunksProcessed: 5,
        totalChunks: 10,
      };

      mockQueueService.getDetectionJobProgress.mockResolvedValue(expectedProgress);

      const result = await controller.getDetectionProgress(jobId);

      expect(result).toEqual(expectedProgress);
      expect(queueService.getDetectionJobProgress).toHaveBeenCalledWith(jobId);
      expect(queueService.getDetectionJobProgress).toHaveBeenCalledTimes(1);
    });

    it('should throw NotFoundException for non-existent job', async () => {
      const jobId = 'non-existent-job';

      mockQueueService.getDetectionJobProgress.mockResolvedValue(null);

      await expect(controller.getDetectionProgress(jobId)).rejects.toThrow(NotFoundException);
      expect(queueService.getDetectionJobProgress).toHaveBeenCalledWith(jobId);
    });

    it('should return completed status when progress is 100%', async () => {
      const jobId = 'completed-job-456';
      const completedProgress = {
        percentage: 100,
        status: 'Analysis complete',
        currentDoc: 'completed-document.txt',
        chunksProcessed: 10,
        totalChunks: 10,
      };

      mockQueueService.getDetectionJobProgress.mockResolvedValue(completedProgress);

      const result = await controller.getDetectionProgress(jobId);

      expect(result.percentage).toBe(100);
      expect(result.status).toBe('Analysis complete');
    });
  });
});
