import { Test, TestingModule } from '@nestjs/testing';
import { DetectController } from './detect.controller';
import { DetectService } from './detect.service';

describe('DetectController', () => {
  let controller: DetectController;
  let service: DetectService;

  const mockDetectService = {
    detectWithFastDetectGPT: jest.fn(),
  };

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      controllers: [DetectController],
      providers: [
        {
          provide: DetectService,
          useValue: mockDetectService,
        },
      ],
    }).compile();

    controller = module.get<DetectController>(DetectController);
    service = module.get<DetectService>(DetectService);
  });

  afterEach(() => {
    jest.clearAllMocks();
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  describe('detectWithFastDetectGPT', () => {
    it('should call service with text and return detection result', async () => {
      const createDetectDto = {
        text: 'This is a sample text for AI detection.',
      };

      const expectedResult = {
        ai_score: 75.5,
        ai_result: 'AI' as const,
        criterion: 0.85,
      };

      mockDetectService.detectWithFastDetectGPT.mockResolvedValue(expectedResult);

      const result = await controller.detectWithFastDetectGPT(createDetectDto);

      expect(result).toEqual(expectedResult);
      expect(service.detectWithFastDetectGPT).toHaveBeenCalledWith(createDetectDto);
      expect(service.detectWithFastDetectGPT).toHaveBeenCalledTimes(1);
    });

    it('should handle AI result', async () => {
      const createDetectDto = {
        text: 'This text is likely generated by AI.',
      };

      const aiResult = {
        ai_score: 90.0,
        ai_result: 'AI' as const,
        criterion: 1.2,
      };

      mockDetectService.detectWithFastDetectGPT.mockResolvedValue(aiResult);

      const result = await controller.detectWithFastDetectGPT(createDetectDto);

      expect(result.ai_result).toBe('AI');
      expect(result.ai_score).toBeGreaterThan(50);
    });

    it('should handle Human result', async () => {
      const createDetectDto = {
        text: 'This text is likely written by a human.',
      };

      const humanResult = {
        ai_score: 20.0,
        ai_result: 'Human' as const,
        criterion: -0.5,
      };

      mockDetectService.detectWithFastDetectGPT.mockResolvedValue(humanResult);

      const result = await controller.detectWithFastDetectGPT(createDetectDto);

      expect(result.ai_result).toBe('Human');
      expect(result.ai_score).toBeLessThan(50);
    });
  });
});
